# common.py
#
# Common file for symbolic constants
# David Lister
# January 2023
#

SPECTRUM_WAVELENGTH_ROW = 1
SPECTRUM_DATA_START_ROW = 4
SPECTRUM_FILE_DELIMITER = '\t'
SPECTRUM_FILE_SKIPLINES = 6

OPTICAL_PROPS_SKIPLINES = 1
OPTICAL_PROPS_DELIMITER = ','

# General Parameters
SUBTRACT_DARK_FROM_CALIBRATION = False
SUBTRACT_DARK_FROM_REFLECTED = True
