# common.py
#
# Common file for symbolic constants
# David Lister
# January 2023
#

# General Parameters
SUBTRACT_DARK_FROM_CALIBRATION = True
SUBTRACT_DARK_FROM_REFLECTED = True
NORMALIZE_REFLECTANCE = False
USE_FLUX = True

SET_SMALL_VALUES_TO_1 = True
SMALL_VALUE_THRESHOLD = 10  # It uses a < operator
LIMIT_TAILS_TO_PEAKS_IN_BOUNDS = True

FIT_LOWER_BOUND_MINIMUM = 400  # nm
FIT_UPPER_BOUND_MAXIMUM = 900  # nm

SLIDER_SCALE_FACTOR = 1000

N_AIR = 1

# File parameters

SPECTRUM_WAVELENGTH_ROW = 1
SPECTRUM_DATA_START_ROW = 4
SPECTRUM_FILE_DELIMITER = '\t'
SPECTRUM_FILE_SKIPLINES = 6
SPECTRUM_FILE_HEADER_LENGTH = 5
SPECTRUM_FILE_EXPOSURE_INDEX = 3

OPTICAL_PROPS_SKIPLINES = 1
OPTICAL_PROPS_DELIMITER = ','

MU = 'µ'
