# common.py
#
# Common file for symbolic constants
# David Lister
# January 2023
#

SPECTRUM_WAVELENGTH_ROW = 1
SPECTRUM_DATA_START_ROW = 4
SPECTRUM_FILE_DELIMITER = '\t'
SPECTRUM_FILE_SKIPLINES = 6

OPTICAL_PROPS_SKIPLINES = 1
OPTICAL_PROPS_DELIMITER = ','

# General Parameters
SUBTRACT_DARK_FROM_CALIBRATION = True
SUBTRACT_DARK_FROM_REFLECTED = True

SET_SMALL_VALUES_TO_1 = True
SMALL_VALUE_THRESHOLD = 10  # It uses a < operator

FIT_LOWER_BOUND_MINIMUM = 350  # nm
FIT_UPPER_BOUND_MAXIMUM = 900  # nm
